inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/initializers/devise.rb'
    - 'config/routes.rb'
    - 'Guardfile'
    - 'app/helpers/ancestry_helper.rb'

# Style

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Layout

# Lint

Lint/UselessAssignment:
  Enabled: true

# Metrics

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Max: 150

Metrics/ModuleLength:
  CountComments: false
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"
    - 'config/environments/*'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 10

# Performance
